name: 'Get Thycotic Secret'
description: 'Gets a secret from Appgate Thycotic service'
inputs:
  thycotic-username:
    description: ''
    required: true
  thycotic-password:
    description: ''
    required: true
  secret-id:
    description: ''
    required: true
  sdp-controller-url:
    description: ''
    required: true
  sdp-username:
    description: ''
    required: true
  sdp-password:
    description: ''
    required: true
outputs:
  secret-value:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.sdp-controller-url}}
    - ${{inputs.sdp-username}}
    - ${{inputs.sdp-password}}
    - ${{inputs.thycotic-username}}
    - ${{inputs.thycotic-password}}
    - ${{inputs.secret-id}}
